// <auto-generated />
using System;
using AltSource.Entity.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AltSource.Entity.Migrations
{
    [DbContext(typeof(AltSourceContext))]
    partial class AltSourceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799");

            modelBuilder.Entity("AltSource.Entity.Clothing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Color");

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("Modified");

                    b.Property<decimal>("Price");

                    b.Property<int>("Size");

                    b.Property<int>("StockUnit");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.ToTable("Clothing");
                });

            modelBuilder.Entity("AltSource.Entity.ClothingRetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ClothingVendorId");

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("Modified");

                    b.Property<decimal>("Price");

                    b.Property<int>("VendorId");

                    b.HasKey("Id");

                    b.HasIndex("ClothingVendorId");

                    b.HasIndex("VendorId");

                    b.ToTable("ClothingRetails");
                });

            modelBuilder.Entity("AltSource.Entity.ClothingVendor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ClothingId");

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("Modified");

                    b.Property<decimal>("Price");

                    b.Property<int>("Unit");

                    b.Property<int>("VendorId");

                    b.HasKey("Id");

                    b.HasIndex("ClothingId");

                    b.HasIndex("VendorId");

                    b.ToTable("ClothingVendors");
                });

            modelBuilder.Entity("AltSource.Entity.Vendor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("AltSource.Entity.ClothingRetail", b =>
                {
                    b.HasOne("AltSource.Entity.ClothingVendor", "ClothingVendor")
                        .WithMany()
                        .HasForeignKey("ClothingVendorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AltSource.Entity.Vendor", "Vendor")
                        .WithMany("ClothingRetails")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AltSource.Entity.ClothingVendor", b =>
                {
                    b.HasOne("AltSource.Entity.Clothing", "Clothing")
                        .WithMany()
                        .HasForeignKey("ClothingId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AltSource.Entity.Vendor", "Vendor")
                        .WithMany("ClothingVendors")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
